services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ms-nest-screaming-app
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ms_nest_screaming_network
    restart: unless-stopped

  redis:
    image: redis:8.0.2
    container_name: ms-nest-screaming-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - ms_nest_screaming_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  ms_nest_screaming_network:
    driver: bridge
    name: ms_nest_screaming_network

volumes:
  redis_data:
    driver: local
    name: ms_nest_screaming_redis_data
