services:
  redis:
    image: redis:8.0.2
    container_name: ms-nest-screaming-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - ms_nest_screaming_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  ms_nest_screaming_network:
    driver: bridge
    name: ms_nest_screaming_network

volumes:
  redis_data:
    driver: local
    name: ms_nest_screaming_redis_data
