FROM node:22.16.0-alpine

RUN apk add --no-cache dumb-init

RUN mkdir -p /usr/src/app \
    && chown -R node:node /usr/src/app

USER node
WORKDIR /usr/src/app

ENV NODE_ENV=development
ENV PORT=3000

COPY --chown=node:node package.json package-lock.json ./

RUN npm ci

COPY --chown=node:node . .

EXPOSE 3000

EXPOSE 9229

ENTRYPOINT ["dumb-init", "--"]
CMD ["npm", "run", "start:dev"]
