export const USER_DETAILS_CACHE_KEY_PREFIX = 'user-details';
export const USER_DETAILS_CACHE_TTL_SECONDS_DEFAULT = 300;
export const USER_DETAILS_CACHE_TTL_SECONDS = process.env
  .USER_DETAILS_CACHE_TTL_SECONDS
  ? Number(process.env.USER_DETAILS_CACHE_TTL_SECONDS)
  : USER_DETAILS_CACHE_TTL_SECONDS_DEFAULT;
